# Лабораторная работа №3. NumPy

## Задание

Выполните следующие задания:

1. Откройте в файл в Google Colab (используйте собственный форк репозитория).
2. Решите задачи.
3. Сохраните результат в ваш репозиторий github в директорию ./les03
4. Создайте pull request в репозиторий https://github.com/chebotarevsa/dap-2024. Название pull request должно иметь формат "<Номер лабораторной работы>  <Номер группы> <ФИО>"
5. Сдайте работу в системе "Пегас", в отчет укажите ссылку на pull request

In [2]:
import numpy as np
np.version.version

'2.0.2'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [2]:
import numpy as np
array = np.random.randint(0, 101, size=(10, 10))
min_value = np.min(array)
max_value = np.max(array)
print("Массив:")
print(array)
print(f"Минимум: {min_value}")
print(f"Максимум: {max_value}")

Массив:
[[ 47  67  94  15   2  82  70  41  10  66]
 [ 54  37  43  99  48   8  71  51  35  39]
 [ 88  51  80  94   2  59  10  28  72  55]
 [ 79  46   2  14  91  71  75   4  66  90]
 [ 27  44  35  90  36   2  51  45  19  12]
 [ 71  62  34  75  76  62  79  29  11  62]
 [ 88  66  30  22  97  35  54  41  48  41]
 [ 85  46 100  39  52  25  97  75   7  90]
 [ 55  19   5  97  52  90  72  65  15  43]
 [ 89  83  26  90  65  39   5  73  38  18]]
Минимум: 2
Максимум: 100


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [3]:
import numpy as np
matrix = np.zeros((8, 8), dtype=int)
for i in range(8):
    for j in range(8):
        if (i + j) % 2 == 0:
            matrix[i, j] = 1
print("8x8 матрица в шахматном порядке:")
print(matrix)

8x8 матрица в шахматном порядке:
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [13]:
import numpy as np

array = np.random.randint(-10, 11, size=11)
print("Исходный массив:")
print(array)

for i in range(len(array)):
    if 3 < array[i] < 8:
        array[i] = -array[i]

print("Массив после изменения знака:")
print(array)

Исходный массив:
[-10  -7   0   9   5   6   8   9  -5  -5   9]
Массив после изменения знака:
[-10  -7   0   9  -5  -6   8   9  -5  -5   9]


4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [35]:
import numpy as np

matrix = np.random.randint(1, 10, size=(5, 5))

print("Исходная матрица:")
print(matrix)

row_means = matrix.mean(axis=1, keepdims=True)

centered_matrix = matrix - row_means

print("\nСредние значения строк:")
print(row_means)

print("\nМатрица после вычитания среднего:")
print(centered_matrix)


Исходная матрица:
[[3 4 8 7 6]
 [4 1 2 8 4]
 [3 8 6 1 9]
 [9 8 1 5 9]
 [6 9 3 7 3]]

Средние значения строк:
[[5.6]
 [3.8]
 [5.4]
 [6.4]
 [5.6]]

Матрица после вычитания среднего:
[[-2.6 -1.6  2.4  1.4  0.4]
 [ 0.2 -2.8 -1.8  4.2  0.2]
 [-2.4  2.6  0.6 -4.4  3.6]
 [ 2.6  1.6 -5.4 -1.4  2.6]
 [ 0.4  3.4 -2.6  1.4 -2.6]]


5. Поменяйте 1 и 2 строки матрицы

In [15]:
import numpy as np
z = np.arange(25).reshape(5, 5)
print("Исходная матрица z:")
print(z)
z[[0, 1]] = z[[1, 0]]
print("\nМатрица после замены 1-й и 2-й строк:")
print(z)

Исходная матрица z:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Матрица после замены 1-й и 2-й строк:
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат,
преобразовать в полярную

---


In [33]:
import numpy as np
cartesian = np.random.randint(-10, 11, size=(10, 2)).astype(float)
print("Декартовы координаты (x, y):")
print(cartesian)
r = np.sqrt(cartesian[:, 0]**2 + cartesian[:, 1]**2)
theta = np.arctan2(cartesian[:, 1], cartesian[:, 0])
polar = np.column_stack((r, theta))
print("\nПолярные координаты (r, θ в радианах):")
print(polar)
theta_deg = np.degrees(theta)
polar_deg = np.column_stack((r, theta_deg))
print("\nПолярные координаты (r, θ в градусах):")
print(polar_deg)

Декартовы координаты (x, y):
[[  9.  -3.]
 [ -6.   0.]
 [  7.  -9.]
 [ -9.  -1.]
 [  5.   7.]
 [  3.   8.]
 [ -4.   4.]
 [-10.  -5.]
 [ -9.  -2.]
 [ -8.   4.]]

Полярные координаты (r, θ в радианах):
[[ 9.48683298 -0.32175055]
 [ 6.          3.14159265]
 [11.40175425 -0.90975316]
 [ 9.05538514 -3.03093543]
 [ 8.60232527  0.95054684]
 [ 8.54400375  1.21202566]
 [ 5.65685425  2.35619449]
 [11.18033989 -2.67794504]
 [ 9.21954446 -2.92292371]
 [ 8.94427191  2.67794504]]

Полярные координаты (r, θ в градусах):
[[   9.48683298  -18.43494882]
 [   6.          180.        ]
 [  11.40175425  -52.12501635]
 [   9.05538514 -173.65980825]
 [   8.60232527   54.46232221]
 [   8.54400375   69.44395478]
 [   5.65685425  135.        ]
 [  11.18033989 -153.43494882]
 [   9.21954446 -167.47119229]
 [   8.94427191  153.43494882]]


7. Заменить максимальный элемент массива на ноль

In [32]:
import numpy as np
z = np.random.randint(0, 100, size=10)
print("Исходный массив z:")
print(z)
max_index = np.argmax(z)
z[max_index] = 0
print("\nМассив после замены максимального элемента на 0:")
print(z)

Исходный массив z:
[72 51  9 13 90 62 72 42 80 18]

Массив после замены максимального элемента на 0:
[72 51  9 13  0 62 72 42 80 18]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [30]:
import numpy as np

array = np.random.randint(0, 101, size=10)

indices = np.random.randint(0, len(array), size=15)

print("Исходный массив:")
print(array)
print("\nИндексы для изменения:")
print(indices)

unique_indices = np.unique(indices)
print("\nУникальные индексы:")
print(unique_indices)

array[unique_indices] += 1

print("\nМассив после изменения:")
print(array)

print("\nИзменённые элементы:")
for idx in unique_indices:
    print(f"  Индекс {idx}: значение увеличено на 1")

Исходный массив:
[63 46 28 30 71 52 87 87 50 92]

Индексы для изменения:
[0 7 3 6 7 0 2 0 3 9 4 2 2 3 4]

Уникальные индексы:
[0 2 3 4 6 7 9]

Массив после изменения:
[64 46 29 31 72 52 88 88 50 93]

Изменённые элементы:
  Индекс 0: значение увеличено на 1
  Индекс 2: значение увеличено на 1
  Индекс 3: значение увеличено на 1
  Индекс 4: значение увеличено на 1
  Индекс 6: значение увеличено на 1
  Индекс 7: значение увеличено на 1
  Индекс 9: значение увеличено на 1


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [36]:
import numpy as np

z = np.array([1, 2, 3, 4, 5])

print("Исходный вектор z:")
print(z)
k = 3
step = k + 1
new_length = len(z) + (len(z) - 1) * k
new_z = np.zeros(new_length)
new_z[::step] = z
print("\nНовый вектор с тремя нулями между каждым значением:")
print(new_z)


Исходный вектор z:
[1 2 3 4 5]

Новый вектор с тремя нулями между каждым значением:
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


10. Найти ближайшее к заданному значению число в заданном массиве

In [37]:
import numpy as np
z = np.arange(100)
v = np.random.uniform(0, 100)
print("Массив z:")
print(z)
print(f"\nЗаданное значение v: {v}")
differences = np.abs(z - v)
closest_index = np.argmin(differences)
closest_value = z[closest_index]
print(f"\nБлижайшее значение: {closest_value} (индекс {closest_index})")

Массив z:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

Заданное значение v: 65.0391606730116

Ближайшее значение: 65 (индекс 65)


## Вопросы




**1**. Какой тип (dtype) будут иметь элементы массива?
``` python
np.array([1, 4, 2, 5, 3])
np.array([1., 4, 2, 5, 3])
np.array([1, 4, 2, 5, 3], dtype='float128')
np.array([1., 4, 2, 5, 3], dtype='complex128')
np.array([1, 4, 2, 5, 3], dtype ='float64')
np.array([1, 4, 2, 5, 3], dtype =int64)
np.array([1, 4, 2, 5, 3], dtype='bool')
np.array([1, 4, 2, 5, 3], dtype='str')
np.array([1, 4, 2, 5, '3'])
np.array([1, -4, 2, 0, 1j])
```
Элементы будут иметь тип complex128, так как наличие комплексного числа 1j приводит к приведению всех элементов к комплексному типу.

**2**. Что будет выведено в консоль и почему?
``` python
np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1'
np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, True], dtype='int64')[-1]
np.array([1, -4, 2, 0, 1j], dtype='int64')[1]
np.array([1, -4, 2, 0, 1j], dtype='str')[-1]
np.array([1, 4, 2, 5, '3'])[-1] * 3
```
```
'41'
-4
False
1
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[1], line 5
      4 np.array([1, -4, 2, 0, True], dtype='int64')[-1]
----> 5 np.array([1, -4, 2, 0, 1j], dtype='int64')[1]

TypeError: can't convert complex to int
```

**3**. Каков результат операции?

``` python
np.ones((3, 5), dtype=float)
np.full((3, 5), 3.14)
np.linspace(0, 1, 5)
np.diag((1,3,5))
np.smile((1,3,5))
np.random.random((3, 3))
np.eye(3)
np.empty(3)
```
```
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_2918/3607915812.py in <cell line: 0>()
      3 np.linspace(0, 1, 5)
      4 np.diag((1,3,5))
----> 5 np.smile((1,3,5))
      6 np.random.random((3, 3))
      7 np.eye(3)

/usr/local/lib/python3.12/dist-packages/numpy/__init__.py in __getattr__(attr)
    408             return char.chararray
    409
--> 410         raise AttributeError("module {!r} has no attribute "
    411                              "{!r}".format(__name__, attr))
    412

AttributeError: module 'numpy' has no attribute 'smile'
```


**4**. Дан двумерный массив X, что будет выведено в консоль?

``` python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
```

``` python
X[0,0]
X[-1,-1]
X[0:1,-1]
X[0:2,-1]
X[0:2,0:2]
X[1,1:3]
X[1,:]
X[1,:]
X[:,:]
X[:]
X[::2,::2]
X[0:3:2,0:3:2]
X[::-1,::-1]
```
```
array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])
```

**5**. Дан двумерный массив grid, в чем различее между операциями?


``` python
grid = np.arange(16).reshape((4, 4))
```

``` python
np.split(grid, [2])
np.split(grid, [2], axis=1)
```
```
Различие заключается в оси, вдоль которой выполняется разделение массива.
В первом случае np.split(grid, [2]) параметр axis не указан, поэтому
используется значение по умолчанию axis=0, что означает разделение массива по
строкам. Индекс 2 указывает на то, что разрыв произойдет после второй строки, в
результате чего функция вернет список из двух массивов формой (2, 4), где
первый массив содержит строки с индексами 0 и 1, а второй массив содержит
строки с индексами 2 и 3. Во втором случае np.split(grid, [2], axis=1) явно
указана ось axis=1, что означает разделение массива по столбцам. Индекс 2
указывает на разрыв после второго столбца, в результате чего функция вернет
список из двух массивов формой (4, 2), где первый массив содержит столбцы с
индексами 0 и 1, а второй массив содержит столбцы с индексами 2 и 3. Таким
образом, первая операция делит матрицу горизонтально на две части по строкам, а
вторая операция делит матрицу вертикально на две части по столбцам.
```


**6**. В чем различие между операциями?

``` python
    [1, 2, 3] + [3, 2, 1]
    np.array([1, 2, 3]) + np.array([3, 2, 1])
```
```
Первая операция выполняет конкатенацию стандартных списков Python, соединяя их
в один список длиной шесть элементов [1, 2, 3, 3, 2, 1]. Вторая операция
выполняет поэлементное арифметическое сложение массивов NumPy, складывая
соответствующие значения с одинаковыми индексами, что дает результат array([4,
4, 4]). Различие заключается в перегрузке оператора плюс для разных типов
данных: для list это объединение последовательностей, а для ndarray это
векторизованная математическая операция.
```

**7**. Как в CodeLab измерить время выполнения кода?
```
В среде выполнения на базе Jupyter Notebook, к которой относится Google Colab,
для измерения времени выполнения кода чаще всего используют магические команды
IPython. Команда %time измеряет время однократного выполнения ячейки или строки
кода и выводит время процессора и реальное время выполнения, а для измерения
всей ячейки используется %%time. Для более точных измерений, особенно для
быстрого кода, используется команда %timeit, которая автоматически запускает
код несколько раз и выводит среднее время выполнения с отклонением. Также можно
использовать стандартный модуль Python time, замеряя разницу между временем до
и после выполнения кода, или модуль timeit для более строгих бенчмарков. В
настройках Google Colab можно включить отображение времени выполнения каждой
ячейки через меню Инструменты и раздел Настройки, где активируется опция показа
времени выполнения ячеек.
```

**8**. Дан массив X, каковы результаты операций?

```python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])

np.sum(M)
np.sum(M, axis=1)
np.sum(M, axis=0)
np.sum(M, axis=2)
np.sum(M, 1)
sum(M)
sum(M,1)
```
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/tmp/ipykernel_1468/2565234765.py in <cell line: 0>()
      3       [1, 6, 7, 7]])
      4
----> 5 np.sum(M)
      6 np.sum(M, axis=1)
      7 np.sum(M, axis=0)

NameError: name 'M' is not defined
```

**9**. Дан массив X, что будет выведено в консоль?

```python
X = np.array([1,2,3,4])

X > 3
X < 3
X[X < 3]
X[X > 3]
X[X != 3]
```
```
[False False False  True]
[ True  True False False]
[1 2]
[4]
[1 2 4]
```

**10**.  В чем преимущество массивов NumPy по сравнению с обычными списками.  Чем обусловлено это преимущество?
```
Главное преимущество массивов NumPy перед обычными списками Python заключается
в значительно более высокой скорости выполнения вычислений и эффективности
использования памяти.
Это преимущество обусловлено следующими факторами:
Однородность данных (Homogeneity): В отличие от списков, которые могут хранить
объекты разных типов, массивы NumPy хранят элементы только одного типа данных
(например, только int32 или float64). Это позволяет хранить данные в
непрерывном блоке памяти без накладных расходов на хранение информации о типе
каждого отдельного элемента, что характерно для объектов Python в списках.
Векторизация (Vectorization): Операции в NumPy выполняются над всем массивом
целиком на уровне компилированного кода (C/C++), избегая медленных циклов
интерпретатора Python. Это устраняет необходимость писать явные циклы for для
перебора элементов.
Локальность данных и кэш-память: Благодаря хранению данных в непрерывном
участке памяти, процессор может эффективнее использовать кэш-память при
обработке массивов, что ускоряет доступ к данным по сравнению со списками, где
элементы могут быть разбросаны в памяти.
Оптимизированные алгоритмы: Библиотека NumPy использует высокооптимизированные
математические библиотеки (такие как BLAS и LAPACK), написанные на
низкоуровневых языках, что обеспечивает максимальную производительность для
линейной алгебры и статистических операций.
```